monitor_fixed_patch:
  _target_: src.callbacks.monitor_fixed_patch.MonitorFixedPatch
  patch_json: data/fixed_patches/fogo_volcano_island_vh_20240502.json
  log_every_n_epochs: 1
  clip_factor: 3.0
  verbose: false
